### ISSUE TITLE
SSLError when trying to connect via SSL

### ISSUE THREAD

**Issue by aviad** [laanwj/bitcoin-python#32]
In [1]: from bitcoinrpc import connect_to_remote

In [2]: from bitcoinrpc.config import read_default_config

In [3]: cfg = read_default_config(None)

In [4]: port = int(cfg.get('rpcport', '18332' if cfg.get('testnet') else '8332'))

In [5]: rpcuser = cfg.get('rpcuser', '')

In [6]: rconn = connect_to_remote(user=rpcuser, password=cfg['rpcpassword'], host='localhost', port=port, use_https=True)

In [7]: rconn.getinfo()
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
/home/ubuntu/src/bitcoin-python/<ipython-input-7-08636fde0d54> in <module>()
----> 1 rconn.getinfo()

/usr/local/lib/python2.7/dist-packages/bitcoin_python-0.2-py2.7.egg/bitcoinrpc/connection.pyc in getinfo(self)
      162         """
      163         try:
--> 164             return ServerInfo(**self.proxy.getinfo())
      165         except JSONRPCException as e:
      166             raise _wrap_exception(e.error)

/usr/local/lib/python2.7/dist-packages/bitcoin_python-0.2-py2.7.egg/bitcoinrpc/proxy.pyc in __call__(self, *args)
       94                   'User-Agent' : USER_AGENT,
       95                   'Authorization' : self.__authhdr,
---> 96                   'Content-type' : 'application/json' })
       97
       98          httpresp = self.__conn.getresponse()

/usr/lib/python2.7/httplib.pyc in request(self, method, url, body, headers)
      956     def request(self, method, url, body=None, headers={}):
      957         """Send a complete request to the server."""
--> 958         self._send_request(method, url, body, headers)
      959
      960     def _set_content_length(self, body):

/usr/lib/python2.7/httplib.pyc in _send_request(self, method, url, body, headers)
      990         for hdr, value in headers.iteritems():
      991             self.putheader(hdr, value)
--> 992         self.endheaders(body)
      993
      994     def getresponse(self, buffering=False):

/usr/lib/python2.7/httplib.pyc in endheaders(self, message_body)
      952         else:
      953             raise CannotSendHeader()
--> 954         self._send_output(message_body)
      955
      956     def request(self, method, url, body=None, headers={}):

/usr/lib/python2.7/httplib.pyc in _send_output(self, message_body)
      812             msg += message_body
      813             message_body = None
--> 814         self.send(msg)
      815         if message_body is not None:
      816             #message_body was not a string (i.e. it is a file) and

/usr/lib/python2.7/httplib.pyc in send(self, data)
      774         if self.sock is None:
      775             if self.auto_open:
--> 776                 self.connect()
      777             else:
      778                 raise NotConnected()

/usr/lib/python2.7/httplib.pyc in connect(self)
     1159                 self.sock = sock
     1160                 self._tunnel()
-> 1161             self.sock = ssl.wrap_socket(sock, self.key_file, self.cert_file)
     1162
     1163     __all__.append("HTTPSConnection")

/usr/lib/python2.7/ssl.pyc in wrap_socket(sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, suppress_ragged_eofs, ciphers)
      379                      do_handshake_on_connect=do_handshake_on_connect,
      380                      suppress_ragged_eofs=suppress_ragged_eofs,
--> 381                      ciphers=ciphers)
      382
      383

/usr/lib/python2.7/ssl.pyc in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, suppress_ragged_eofs, ciphers)
      141                                         ciphers)
      142             if do_handshake_on_connect:
--> 143                 self.do_handshake()
      144         self.keyfile = keyfile
      145         self.certfile = certfile

/usr/lib/python2.7/ssl.pyc in do_handshake(self)
      303         """Perform a TLS/SSL handshake."""
      304
--> 305         self._sslobj.do_handshake()
      306
      307     def _real_connect(self, addr, return_errno):

SSLError: [Errno 8] _ssl.c:504: EOF occurred in violation of protocol

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
