### ISSUE TITLE
[QUESTION] Cancelling Unconfirmed Transaction

### ISSUE THREAD

**Issue by fjcaetano** [laanwj/bitcoin-python#48]
Hi,

First of all, thanks for this repo. It has helped me a lot!

This is no issue (at least for now), but I couldn't find anything in the docs, so I thought I should ask: Is it possible to cancel a transaction with 0 confirmations?

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
