### ISSUE TITLE
listsinceblock doesn't take a minimum confirmations argument

### ISSUE THREAD

**Issue by mniip** [laanwj/bitcoin-python#57]
According to [Bitcoin wiki](https://en.bitcoin.it/wiki/Original_Bitcoin_client/API_calls_list):

> listsinceblock	 [blockhash] [target-confirmations]
> Get all transactions in blocks since block [blockhash], or all transactions if omitted. [target-confirmations] intentionally does not affect the list of returned transactions, but only affects the returned "lastblock" value.

Can be fixed with a two-line change in `connection.py`.

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
