### ISSUE TITLE
Pruning the blockchain

### ISSUE THREAD

**Issue by Jzarecta** [laanwj/bitcoin-python#60]
I want to run a bitcoin app on my vps, but the blockchain is prohibitly big for it, I heard I could **prune** the blockchain to the size I wish. I wonder if there is a way to use pruning settings on this library, or if an alternative method is suggested for it.

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
